package static

//nolint:gochecknoglobals,lll
var storage = []string{
	`People change easily. Deal with it.`,
	`Five simple rules for happiness:  - Free your heart from hatred. - Free your mind from worries. - Live simply. - Give more. - Expect less.`,
	`We get attached to temporary things, then wonder why our happiness never lasts.`,
	`making someone else happy is one of the best feelings`,
	`Never be afraid of change. You may lose something good, but you may gain something even better`,
	`Because when something happens, she’s the person I want to tell. The most basic indicator of love.`,
	`It is a frightening thought, that in one fraction of a moment you can fall in the kind of love that takes a lifetime to get over.`,
	`Being beautiful has nothing to do with physical appearance. Its your character as a person, its how you make others feel about themselves`,
	`True love will always find a way to come back.`,
	`There’s a special place in my heart for the ones who were with me at my lowest and still loved me when I wasn’t very loveable.`,
	`Don’t feel bad for making a decision that upsets other people. You’re not responsible for their happiness. You’re responsible for yours.`,
	`stop letting people make you feel bad or embarrassed about doing what makes you happy. find what you love and do more of it. never apologize`,
	`Being nice to someone you hate doesn’t mean you’re fake. It means you’re mature enough to tolerate your hate towards them.`,
	`I’m not perfect. I’ll annoy you, tick you off but put all that aside, You’ll never find someone who cares and loves you more than me.`,
	`Someday you’re going to meet someone who makes you happy, feel beautiful, and stands by you even when you feel like you don’t deserve them.`,
	`It’s not called "giving up" when you know you’ve fully tried your best. So don’t blame yourself for someone else’s lack of appreciation.`,
	`Don’t trust the things your heart tells you when it’s sad.`,
	`If you have a family that loves you, a few good friends, food on your table and a roof over your head. You are richer than you think.`,
	`relax, u’ll graduate, u’ll get a job, u’ll become an adult, u’ll find someone who loves you. u have an entire life. things take time`,
	`The saddest people try their best to make people happy. They know what it’s like to feel worthless, they don’t want anyone to feel that.`,
	`I feel really happy when I see you, because when I look at you and see your smile, it also makes me have a smile.`,
	`Psychology says, always go with the choice that scares you the most, because that’s the one that is going to help you grow`,
	`The world will knock you down plenty. You don’t need to be doing it to yourself.`,
	`The most selfless thing I’ve ever done was fighting the urge to ask you to stay.`,
	`Expect less, prepare more. Judge less, respect more. Complain less, thank more. Regret less, smile more.`,
	`To everyone that says love sucks: love is the best thing that could possibly happen to you, it's pure happiness. You will have it one day.`,
	`Sometimes you find yourself in the middle of nowhere, and sometimes in the middle of nowhere, you find yourself.`,
	`You’ll end up really disappointed if you think people will do for you as you do for them. Not everyone has the same heart as you.`,
	`Success begins with dreams, that turn into desires, which become actions that don’t stop until they bring results.`,
	`The minute you think of giving up, think of the reason why you held on so long.`,
	`Don’t waste your time on someone who doesn’t bother to learn anything about you.`,
	`One of the greatest tragedies in life is to lose your own sense of self and accept the version of you that is expected by everyone else.`,
	`Help people and watch them grow.`,
	`Love your parents. Show it before too late.`,
	`As you grow older, you realize it becomes less important to have more friends and more important to have real ones.`,
	`I have loved you for a thousand years, I’ll love you for a thousand more.`,
	`No matter how dark the moment, love and hope are always possible.`,
	`Be happy not because everything is good, but because you can see the good side of everything.`,
	`That awkward moment when you hear something that kills you inside, but you have to act like you’re fine.`,
	`i love friends that keep you grounded &amp; aren’t afraid to tell you when you’re wrong/being a complete idiot like those are real friendships`,
	`Remove toxic people from your life.  Free yourself.`,
	`Every generation looks back on previous generations and says, "That was really dumb. Why did they do/think/believe that?`,
	`I'm so good at beginnings, but in the end I always seem to destroy everything, including myself.`,
	`Everyone comes into your life for a reason, some for good or bad, they may shape us, break us, but in the end they make us who we are.`,
	`I am what I am. I like what I like. I love what I love. I do what I want. Get off my back and deal with it. It’s my life, not yours.`,
	`Being appreciated is such a nice feeling.`,
	`No one deserves to be disrespected.`,
	`Life without my crazy friends would be so boring.`,
	`I love sleep. You forget about pain, problems, stress, everything for a while.`,
	`When you truly care for someone, their mistakes never change your feelings because it’s the mind that gets angry but the heart still cares.`,
	`The older I get, the more I realize adults don’t know what they’re doing either and are just pretending to have it together.`,
	`In the end you’ll see who’s fake, who’s true, and who will risk it all for you.`,
	`Worrying is a big waste of time.`,
	`I am who I am. Nobody said you have to like me.`,
	`Don’t trust words, trust actions.`,
	`People are temporary nowadays.`,
	`Take a chance, you never know what might happen.`,
	`you don’t hate life. you just hate the fact that things are not going according to how you want it.`,
	`The only words that truly hurt are the ones that come from the people you most care about.`,
	`Mistakes are part of the fun.`,
	`Never ignore a person who loves you and cares for you.`,
	`My favorite place is inside your hug.`,
	`In the end, we only regret the chances we didn’t take.`,
	`I hate being ignored. I feel so pathetic trying to get your attention.`,
	`I fell in love with your personality, your looks are just a bonus.`,
	`I am aware that I am less than some people prefer me to be, but most people are unaware that I am so much more than what they see.`,
	`No one knows what you feel inside.`,
	`Do whatever you wanna do, its your life, be happy.`,
	`It’s so sweet when someone texts you after you hang out just to say they had fun with you. Little things like that makes life great.`,
	`Maybe I’m scared because you mean more to me than any other person. You are everything I think about, everything I need, everything I want.`,
	`Life always offers you a second chance. Its called tomorrow.`,
	`Sometimes bad decisions make good stories.`,
	`The truth will set you free. But first, it will piss you off.`,
	`Real girls are hard to get. Real boys are brave to wait.`,
	`Late night conversations are the best.`,
	`Make yourself a priority. At the end of the day, you’re your longest commitment.`,
	`Spend life with the people who make you happy, not the people who you have to impress.`,
	`i hate that feeling when you’re not necessarily sad, but you just feel really empty.`,
	`The best thing in life is finding someone who knows all your mistakes and weaknesses and still thinks you’re completely amazing.`,
	`Judging me won’t make you awesome.`,
	`dont take me for granted`,
	`Someday it’s gonna make sense.`,
	`Fall in love with somebody who will never let you go to sleep wondering if you still matter.`,
	`Protecting your own happiness isn’t selfish. You deserve every ounce of happiness.`,
	`One look, one smile, one word, one hug, one text, one call, they can all mean so much when it’s from that special person.`,
	`I am who I am Your approval is not needed.`,
	`when I’m on the phone with my mom: me: ok me: ok me: ok me: ok me: ok me: ok me: ok me: bye me: ok me: ok me: ok me: ok me: ok me: ok`,
	`Nothing’s more fun than doing what people say you can’t do!`,
	`You need someone who goes out of their way to make it obvious that they want u in their life`,
	`Sometimes having a big heart sucks, you expect everyone to care as much as you do, and that’s just not the case.`,
	`Don’t love too soon. Don’t trust too fast. Don’t judge too soon. Don’t quit too early. Don’t expect too high. Don’t talk too much`,
	`Freedom means you are unobstructed in living your life as you choose. Anything less is a form of slavery. – Wayne Dyer`,
	`Forgiving is easy. Trusting again, not so much.`,
	`Someone who wants the best for you is what’s best for you. Remember that.`,
	`I fall, I rise, I make mistakes, I live, I learn, I’ve been hurt but I’m alive. I’m human, I’m not perfect but I’m thankful.`,
	`Don’t say "sorry" and then do it all over again.`,
	`Don’t listen to the crowd. Listen to your own soul.`,
	`i hate how one minute im perfectly content then the next minute im ready to throw myself in front of a car`,
	`I love those random memories that make me smile no matter what is going on in my life right now.`,
	`It’s nice being appreciated. It’s even better being loved.`,
	`Apologizing does not always mean you are wrong; it just means that you value your relationships more than your ego.`,
	`If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.`,
	`the only thing i learned in math is that i hate math`,
	`People say you don’t know what you’ve got until it’s gone. Truth is, you knew what you had, you just never thought you’d lose it.`,
	`Some people will never appreciate what you do for them.`,
	`My only relationship goal is someone who motivates me to become a better person and shows me the potential I don’t see in myself.`,
	`The best love story is when you fall in love with the most unexpected person at the most unexpected time.`,
	`Don’t make decisions when you’re mad, you’ll regret it.`,
	`Can’t stop thinking about your beautiful smile.`,
	`The best way I can love you is by not losing myself in you, but growing with you.`,
	`Don’t tell people your plans. Show them your results.`,
	`Everyone in life is gonna hurt you, you just have to figure out which people are worth the pain.`,
	`If you’re lucky enough to get a second chance at something, don’t waste it.`,
	`Surround yourself with people who try to better you, not people who try to BE better than you.`,
	`Maybe we feel empty because we leave pieces of ourselves in everything we used to love.`,
	`I still fall for you everyday.`,
	`True friends never count things. They count memories. 👌`,
	`I want to be with you, it is as simple, and as complicated as that.`,
	`Be the change you wanna see.`,
	`I need a hug. A long, tight hug.`,
	`unexpected phone calls are cute`,
	`Don’t talk, act. Don’t say, show. Don’t promise, prove.`,
	`Always tell someone how you feel, because opportunities are lost in the blink of an eye but regret can last for a lifetime.`,
	`Sometimes you just have to accept that some people can only be in your heart, not in your life.`,
	`Why do we try so hard for people that don’t even try for us.`,
	`you don’t realize how poorly you’ve been treated in the past until someone comes along and treats you the way you should be treated.`,
	`Never apologize for saying what you feel, its like saying sorry for being real.`,
	`If you hold back how you feel because you’re afraid of getting hurt you end up hurt anyway.`,
	`I have always loved too much, or not enough.`,
	`A relationship is not based on the length of time you spent together, its based on the foundation you built together.`,
	`I love people who are open-minded. People who just vibe with whatever you talk about. You can talk about anything and everything.`,
	`i grew out of "i never text first" phase since i realized nothing was wrong with showing someone you care about them more than your pride`,
	`I’m so happy I met you.`,
	`The worst thing in the world can happen, but the next day the sun will come up. And you will eat your toast. And you will drink your tea.`,
	`Smile, because although you may be having a bad day, you have food, clean water, clothes, a home and your health`,
	`I just want to pour my soul out on someone and not have to worry about the mess I’ve made.`,
	`How you make others feel about themselves says a lot about you.`,
	`I don’t chase people anymore. I learned that I’m here, and I’m important. I’m not going to run after people to prove that I matter.`,
	`One of the best feelings in the world is knowing that your presence and absence both mean something to someone.`,
	`It’s crazy how when you’re really into someone, you don’t even notice anyone else.`,
	`I want to go home. The hard part is, I haven’t figured out where home is.`,
	`Everything has changed and yet, I am more me than I’ve ever been.`,
	`If you have to convince someone you’re right for them, they’re not right for you.`,
	`sometimes i’m at war with everything inside me`,
	`Take chances but be organised.`,
	`Do what you feel in your heart to be right – for you’ll be criticized anyway.`,
	`When it’s something real, you just know.`,
	`I can be someone’s and still be my own.`,
	`One day, someone will walk into your life and make you see why it never worked out with anyone else.`,
	`I want to be someone’s favorite person to talk to.`,
	`Eventually soulmates meet, for they have the same hiding place.`,
	`The 3 C’s of life: choices, chances, and changes. You must make a choice to take a chance or your life will never change.`,
	`No, I’m not ok. But I haven’t been ok since I was 11, maybe 12. I am still here though. ⁰I’m still breathing. That will have to be enough.`,
	`Love never leaves, people do.`,
	`I remember I used to be afraid of being alone.. now, I’m afraid of having the wrong people as company.`,
	`When you stop chasing the wrong things you give the right things a chance to catch you.`,
	`You either like me or you don’t. It took me years to learn how to love myself, I don’t have that kinda time to convince somebody else.`,
	`I like long text messages because I appreciate a complete thought.`,
	`Have fun, even if it’s not the same kind of fun everyone else is having.`,
	`A couple years from now, everything you’re stressing about won’t mean a thing.`,
	`I understand that nobody understands me, but I can’t be someone I’m not.`,
	`There are a million ways to bleed. But you are by far my favourite. `,
	`She put me back together so well that I forgot I was broken.`,
	`A friend is someone who can see the truth and pain in you even when you are fooling everyone else.`,
	`i’m so grateful for the people who don’t give up on me and are patient with me while i’m distant and trying to figure myself out`,
	`What am I even fighting for?`,
	`Just because I let you go doesn’t mean I wanted to.`,
	`me? overreacting? probably`,
	`Tell me every terrible thing you ever did, and let me love you anyway.`,
	`What if you don’t complete the person that completes you?`,
	`Maybe a soulmate is someone who understands the very deepest parts of you without you having to explain.`,
	`if you care about someone then show it`,
	`A true friend is someone who understands your past, believes in your future, and accepts you today just the way you are.`,
	`strict parents raise the best liars`,
	`You are so brave and quiet, I forget you are suffering.`,
	`It’s depressing seeing how many people give up on their dreams at a young age because they’re told to “be realistic”.`,
	`We kissed a lot but it didn’t feel like love.`,
	`Any fool can know. The point is to understand.`,
	`I wish people were more straight-up with things.`,
	`I haven’t felt so upset in awhile. I feel that the sadness is slowly eating away all the pieces inside me.`,
	`Don’t change yourself to win someone’s heart. Stay true and you’ll find someone who likes you for being you`,
	`The more I threw away, the more I found.`,
	`It was nice while it lasted`,
	`There’s nothing wrong with you. There’s something wrong with the world you live in.`,
	`Forever is a little hard to say, enjoy while you still can.`,
	`Silence is the best way to let someone know they did you wrong.`,
	`It’s the ones you love the most who can lift you in an instant, and destroy you without trying.`,
	`These pains you feel are messengers. Listen to them.`,
	`Stop hating yourself for everything you aren’t. Start loving yourself for everything you are.`,
	`There’s a story behind every person. There’s a reason why they’re the way they are. Think about that before you judge someone.`,
	`Here is the world. Beautiful and terrible things will happen. Don’t be afraid. I am with you.`,
	`Stay strong.`,
	`You’re scared of the way I make you feel because you don’t want to feel anything.`,
	`No relationship is ever perfect but working through the imperfections is what keeps us going.`,
	`Love is sweet when it’s new. But it is sweeter when it’s true.`,
	`Of course I love you, it is my fault that you have not known it all the while.`,
	`A relationship where you can act like complete idiots together is probably the best thing ever.`,
	`I don’t dislike learning, I dislike how we are taught`,
	`If you want to be free, all you have to do is let go.`,
	`so many years of education yet nobody ever taught us how to love ourselves and why its so important`,
	`One day you’ll realize how much I cared`,
	`The worst loneliness is to not be comfortable with yourself.`,
	`You are never as broken as you think you are.`,
	`Good relationships don’t just happen. They take time, patience, and two people who truly want to be together.`,
	`Only a few people care. The rest are just curious`,
	`Stop crying over yesterday and start smiling for tomorrow.`,
	`Every good thing that has happened in your life happened because something changed.`,
	`The person you think of when you stand in front of the ocean. That’s the person you’re in love with.`,
	`I hate it when I’m trying to be serious, but then I accidentally smile.`,
	`It’s not selfish to love yourself, take care of yourself, and to make your happiness a priority. It’s necessary.`,
	`Will you still love me tomorrow?`,
	`Just because a person smiles all the time, doesn’t mean their life is perfect cause a smile can hide so much.`,
	`Just because I don’t react doesn’t mean I don’t notice.`,
	`Before you give up.. Think about why you held on for so long..`,
	`Do you think the universe fights for souls to be together? Some things are too strange and strong to be coincidences.`,
	`I still remember how we first started talking.`,
	`When you really care about someone, their happiness matters more than yours.`,
	`One of the hardest decisions you’ll ever face in life is choosing whether to walk away or try harder.`,
	`It’s about who you miss at 2 in the afternoon when you’re busy, not at 2 in the morning when you’re lonely.`,
	`My mom is the strongest woman I know.`,
	`I want to tell someone everything.`,
	`I love my mom no matter what we go through, no matter how much we argue, because I know, at the end, she’ll always be there.`,
	`Before I met you, I never knew what it was like to be able to look at someone and smile for no reason.`,
	`That’s what people do who love you. They put their arms around you and love you when you’re not so lovable.`,
	`We need patience on everything.`,
	`Don’t sacrifice your time for people who wouldn’t do the same for you.`,
	`Always respect other peoples’ feelings.`,
	`3 most painful things: trying to hide what you really feel, loving someone who loves another, and taking risk to fall in love again.`,
	`When someone really likes you, they will never hurt you. And if they do, you can see it in their eyes that it hurts them too.`,
	`When you start seeing your worth, you’ll find it harder to stay around people who don’t.`,
	`We were both so ugly inside. But we made each other beautiful.`,
	`I wonder how many people I’ve looked at all my life and never seen.`,
	`Looks will fade, attitude won’t Stay classy, but never trashy.`,
	`But I tried, didn’t I? Goddamnit, at least I did that.`,
	`One small positive thought in the morning can change your whole day.`,
	`Work hard in silence; let success make the noise.`,
	`Learn to appreciate before you complain.`,
	`I remember I loved her. And I remember she left. Everything else is a blur.`,
	`Caught between a strong mind and a fragile heart.`,
	`Don’t be an open book.If someone reads a wrong page they might not want to know the rest of the story. Make sure your trust is hard earned`,
	`I wish I could have stayed in your life, but I was too much and not enough at the same time.`,
	`*Making mistakes is better than faking perfection.*`,
	`Never give up on someone you can’t go a day without thinking about.`,
	`I am overflowing with words I do not have.`,
	`Not sure if i’m hungry, or just bored.`,
	`I don’t believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.`,
	`A true relationship is someone who accepts your past, supports your present, loves you and encourages your future.`,
	`Mom, thanks for always being there, I just love you so much.`,
	`You know someone means a lot to you when their mood can easily affect yours.`,
	`I hate getting flashbacks from things I don’t want to remember.`,
	`It’s better to be unhappy alone than unhappy with someone.`,
	`Whoever in you life, probably needs your time.`,
	`Live a life you are proud of.`,
	`We look up at the same stars, and see such different things.`,
	`Failure is better than never trying at all.`,
	`My life is a struggle between my need for acceptance, my fear of rejection, and a desire to not care at all.`,
	`You don’t always get what you wish for, you get what you work for`,
	`…But our ears are too small for our hearts to understand the words inside.`,
	`A person who truly loves you, is someone who sees the pain in your eyes, while everyone else believes in the smile on your face.`,
	`Being happy doesn’t mean that everything is perfect It means that you’ve decided to look beyond the problems.`,
	`I want you always to remember me. Will you remember that I existed, and that I stood next to you here like this?`,
	`I miss how happy I used to be when I was a little kid.`,
	`Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.`,
	`It is a mark of maturity when someone hurts you, and you try to understand them.`,
	`*Beauty attracts the eyes, but personality captures the soul.*`,
	`I can’t understand why emptiness is the heaviest feeling of all.`,
	`When you say yes to others, make sure you are not saying no to yourself.`,
	`I never fall apart, because I never fall together.`,
	`Live life to express, not to impress.`,
	`I do not understand why you would go out of your way to hurt each other, when life can already hurt so much.`,
	`We are what we pretend to be, so we must be careful about what we pretend to be.`,
	`I admire people who choose to shine even after all the storms they’ve been through.`,
	`I don’t want a lukewarm love. I want it to burn my lips and engulf my soul.`,
	`Sometimes you need to stop whatever you’re doing and just look around... what are you doing?`,
	`Twitter is like life, you’ve just gotta post what you feel, retweet the good memories, delete the drama and follow your dreams.`,
	`Happiness is not something you postpone for the future; it is something you design for the present.`,
	`Some hearts understand each other even in silence.`,
	`The expert in anything was once a beginner.`,
	`That’s why love is madness. It’s too easy to lose your mind when you lose your heart.`,
	`I don’t want perfect, I want real.`,
	`Forgive yourself. Not just once. Again, and again, and again. As many times as it takes to find peace.`,
	`Smile is always the choice. No matter if you have sorrow, or anything else`,
	`Most of the problems in your life are due to two reasons: you act without thinking, or think without acting.`,
	`Stay strong, be positive. We all struggle sometimes.`,
	`We need to know ourselves... to understand others better.`,
	`I am so sorry to all the people I hurt while I was hurting.`,
	`Top 3 Lies: - I’m sorry - I hate you - I love you`,
	`It gives me strength to have somebody to fight for; I can never fight for myself, but, for others, I can`,
	`If you wait until you’re ready, you’ll be waiting the rest of your life.`,
	`People who understand sarcasm well are often good at reading people’s mind. They understand that the other has something else in mind.`,
	`Isn’t it ironic that we bury people even deeper beneath the ground in hopes they make it to the sky?`,
	`Stop rushing into relationships and start building friendships, strong foundations first, everything else second.`,
	`When I give, I give myself.`,
	`You can’t stop something that’s inside you.`,
	`Nobody looks good in their darkest hours. But it’s those hours that make us what we are.`,
	`People think you’re crazy if you talk about things they don’t understand.`,
	`Be smart enough to hold on, be brave enough to let it go.`,
	`No matter how far you have gone on the wrong road, you can still turn around.`,
	`Don’t lose yourself just because you found somebody.`,
	`Daily reminder: You don’t have to please anyone`,
	`Never apologize for burning too brightly or collapsing into yourself every night. That is how galaxies are made.`,
	`How beautiful to find a heart that loves you, without asking you for anything, but to be okay.`,
	`If you can love the wrong one so much, just imagine how much you can love the right one.`,
	`And there were times when I knew how you felt and it was hell to know it.`,
	`Do all the good you can, to as many people as you can, as often as you can.`,
	`You will burn and you will burn out; you will be healed and come back again.`,
	`Happiness is the best revenge`,
	`story of my life: i knew better but i did it anyway`,
	`Stay strong. Even when it feels like everything is falling apart.`,
	`He felt happy these days, yet there was always an undercurrent of sadness just below the surface.`,
	`But the heart has its own memory and I have forgotten nothing.`,
	`Sometimes I wish I could read your mind. Then, I wonder if I could handle the truth.`,
	`I didn’t change, I just see things differently now.`,
	`I myself am made entirely of flaws, stitched together with good intentions.`,
	` Understanding is knowing that you don’t have to understand.`,
	`Home isn’t a place, it’s a feeling.`,
	`Beauty without brain is useless.`,
	`I’m honestly not a bad person, my heart is in the right place; it’s just that my head isn’t.`,
	`The further inside you hide the hurt, the more it hurts inside. All wounds need air to heal.`,
	`Use your brain to protect your heart from pain.`,
	`I am a strong person, but every once in a while, I wish someone would hold my hand and tell me that everything’s going to be ok.`,
	`Life is too short to wake up with regrets. So love the people who treat you right and forget about the ones who don’t.`,
	`Because in the end, you won’t remember the time you spent working in the office or mowing your lawn. Climb that goddamn mountain.`,
	`It’s crazy how fast everything can change.`,
	`Your smile is literally the cutest thing I have ever seen in my life.`,
	`Lost is a lovely place to find yourself.`,
	`Wherever you go, go with all your heart.`,
	`I don’t know what my future holds, but I’m hoping you’re in it.`,
	`You have to be odd to be number one.`,
	`You deserve someone who knows how to make things up to you after hurting you. Not someone who is very good with just the word "sorry".`,
	`Either write something worth reading or do something worth writing.`,
	`Believe in yourself, even when everyone else doesn’t.`,
	`Someone you haven’t even met yet is wondering what it’d be like to know someone like you.`,
	`Nobody can change a person, but someone can be the reason for a person to change.`,
	`I’m so addicted to the idea of you and I being together one day.`,
	`I’m the crazy one who thinks that words reach people.`,
	`Far too many people are looking for the right person, instead of trying to be the right person.`,
	`When someone is in your heart, they’re never truly gone. They can come back to you, even at unlikely times.`,
	`The worst lies are the ones you tell yourself.`,
	`Act with kindness but do not expect gratitude.`,
	`I’m not mad. I’m hurt. There’s a difference.`,
	`Saying "I’m tired" when you’re actually sad.`,
	`The mind is a funny place. I do not even trust my own.`,
	`Nothing can wear you out like caring about people.`,
	`Love, it will not betray you, dismay or enslave you. It will set you free`,
	`I have lost and loved and won and cried myself to the person I am today.`,
	`Respect your parents They passed school without google.`,
	`Don’t be afraid of any rejections. It’s part of our life.`,
	`You are what won’t let you sleep.`,
	`They say a person needs just three things to be truly happy in this world: someone to love, something to do, and something to hope for.`,
	`Sometimes a perfect memory can be ruined if put to words.`,
	`I knew the second I met you that there was something about you I needed. Turns out it wasn’t something about you at all. It was just you.`,
	`Never look back on past mistakes, learn from them and move forward, let it go.`,
	`Never make fun of someone’s passion because that’s the thing that saves them from the world`,
	`Do not feel lonely, the entire universe is inside you.`,
	`Forget those who forget you.`,
	`I left because you never asked me to stay.`,
	`Do it. Make them proud.`,
	`You’re too beautiful to be cheated on.`,
	`If you can’t get someone off your mind they are probably supposed to be there.`,
	`I made myself from all the love you no longer wanted.`,
	`I made my own twitter so I tweet how I like.`,
	`Write her a letter, send her a flower, love only gets old if you let it.`,
	`Everyone is a moon, and has a dark side which they never show to anybody.`,
	`It’s okay to live a life others don’t understand.`,
	`Remember, the best is yet to come.`,
	`Be strong, no matter how hard things may seem.`,
	`The way you see yourself, and the way I see you, are two very different things.`,
	`Don’t leave a girl you need, for a girl you want.`,
	`The best way to be happy is to turn the negatives into positives.`,
	`Once you’ve accepted your flaws, no one can use them against you.`,
	`Nobody catches my eye like you.`,
	`Stay strong and make them wonder how you’re still smiling.`,
	`Don’t kiss me if you’re afraid of thunder. My life is a storm.`,
	`It is so incredibly nice for somebody to notice your absence.`,
	`It’s a beautiful thing when you get so comfortable with someone and you realize you’re telling them things you’ve never said out loud before`,
	`Appreciate what you have right now, because you don’t always get a second chance.`,
	`I think part of the reason why we hold so tight is because we fear something so great won’t happen twice`,
	`I like person who appreciate my weird personality.`,
	`Hope for the best and take whatever comes.`,
	`Time doesn’t really heals wound but with the help of acceptance, it does.`,
	`Sometimes suffering is just suffering. It doesn’t make you stronger. It doesn’t build character. It only hurts.`,
	`Sadness don’t choose its victims. Everyone has to feel sadness in order to enjoy happiness.`,
	`Letting go means you’re strong enough.`,
	`We could have been happy. I know that, and it is perhaps the hardest thing to know.`,
	`The tighter the hug the better it feels.`,
	`My favorite texts are the ones where you re-read and it still puts a smile on your face like it’s the first time you read it.`,
	`True friends accept you exactly as you are.`,
	`You don’t always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens.`,
	`I don’t care who you are, I don’t care how you look, I don’t care where you’re from, if you can make me laugh then I like you.`,
	`The desire to reach for the stars is ambitious. The desire to reach hearts is wise.`,
	`Hope but never expect. Look forward but never wait.`,
	`Bitterness will block blessings in your life.`,
	`Don’t get burned twice by the same flame.`,
	`And even if you’re not here to stay, I’m happy the universe allowed your soul to stop by.`,
	`No matter how honestly you open up to someone, there are still things you cannot reveal.`,
	`I’m sorry I can’t be perfect. 😞💔`,
	`Randomly remembering the good times and smiling like a idiot.`,
	`Pain makes you stronger. Fear makes you braver. Heartbreaks make you wiser.`,
	`I’m just thankful for the people that never left me.`,
	`The person who laughs the most, cries the hardest inside.`,
	`Do what you love to help others and you will always love what you do.`,
	`Tweet like nobody’s following or reading or judging.`,
	`Train your mind to see the good in everything.`,
	`Sometimes all we need is a fresh start.`,
	`I will try to be perfect but i won’t try to be fake.`,
	`The older I get, the more I realize what really matters in life.`,
	`I can’t promise you a perfect relationship, but what I can promise you is that if you’re trying, I’m staying.`,
	`Know your priorities.`,
	`If you love deeply, you’re going to get hurt badly. But it’s still worth it.`,
	`Be with someone who can see you for what you are worth.`,
	`Note to self: “I love you” does not mean “I won’t ever leave you.`,
	`I want to hug you and never let go. 💓`,
	`Remember that everyone you meet is afraid of something, loves something and has lost something.`,
	`I appreciate effort. No matter how small, silly or irrelevant, I appreciate effort.`,
	`I don’t want to be your whole life, just your favorite part.`,
	`Sometimes we don’t need advice. We just need somebody to listen.`,
	`The quieter you become, the more you can hear.`,
	`And in the end, we were all just humans.. drunk on the idea that love, only love, could heal our brokenness.`,
	`People change and forget to tell each other.`,
	`Isn’t it scary knowing that any time could be the last time you talk to someone? Always keep that in mind.`,
	`when you like someone so much you actually listen to the music they send you`,
	`People are very fond of giving away what they need most themselves.`,
	`Don’t let one bad day make you feel like you have a bad life.`,
	`I always find myself comforting people with the words I want someone to say to me`,
	`Sometimes, you need to be alone. Not to be lonely, but to enjoy your free time being yourself.`,
	`Be silly. Be honest. Be kind.`,
	`Sometimes the most ordinary things can be made extraordinary by doing them with the right people.`,
	`you’re the only thing on my mind lately, and i’m not sure why, i just know you’ve made me feel more like myself than I’ve felt in years.`,
	`No matter how far you travel, you can never get away from yourself.`,
	`You were put on this earth to achieve your greatest self, to live out your purpose, and to do it courageously.`,
	`I knew I would wish for that moment back every day of my life, so I lived it with everything I had.`,
	`I want to heal with you and build something better.`,
	`Smile because life is too short to be unhappy`,
	`Everybody has gone through something that has changed them in a way that they could never go back to the person they once were.`,
	`If I’m weird around you, that means I’m comfortable with you.`,
	`I want someone who feels lucky to have me.`,
	`That’s when you know you’ve found somebody really special. When you can just shut the fuck up for a minute and comfortably share silence.`,
	`Better days are coming. Hang in there.`,
	`I still catch myself feeling sad about things that don’t matter anymore.`,
	`Don’t get lost in your pain, know that one day your pain will become your cure.`,
	`Aprreciate every efforts.`,
	`You don’t just stop loving someone because they don’t love you back.`,
	`Good things come to those who work hard, while others are whining.`,
	`The more you hold on to these bad memories, the more it’s going to hurt.`,
	`A person learns how to love himself through the simple acts of loving and being loved by someone else.`,
	`It’s crazy how much you’ll tolerate for someone you care about.`,
	`I don’t want perfect, I want honest.`,
	`A single person is missing for you, and the whole world is empty.`,
	`I like it when somebody gets excited about something. It’s nice.`,
	`A relationship with no arguments, is a relationship with a lot of secrets.`,
	`Trust the vibes you get, energy doesn’t lie.`,
	`It’s been very rare to have known you, very strange and wonderful.`,
	`Eye contact is way more intimate than words will ever be.`,
	`You smile, but you wanna cry. You talk, but you wanna be quiet. You pretend like you’re happy, but you aren’t.`,
	`I like it when it rains hard. It sounds like white noise everywhere, which is like silence but not empty.`,
	`It’s great to be happy, but it’s even better to bring happiness to others.`,
	`What about when someone doesn’t need a shoulder? What if they need the arms?`,
	`I wonder if you ever talked about me to someone.`,
	`Find me now. Before someone else does.`,
	`Hate me for who I am, I don’t care At least i’m not pretending to be someone i’m not.`,
	`But someday I’m going to find somebody and love him and love him and never let him go.`,
	`Your twenties are a time of exploration, not certainty. Get out and try, don’t sit at home thinking you should already know.`,
	`I just want you to be happy. If that’s with me or with someone else or with nobody. I just want you to be happy.`,
	`The loneliest moment in someone’s life is when they are watching their whole world fall apart, and all they can do is stare blankly.`,
	`Finding you was like coming home.`,
	`Maybe, no matter how much you loved them, they could slip through your fingers like water, and there was nothing you could do about it.`,
	`When love is real, it finds a way.`,
	`Some talk to you in their free time, and some free their time to talk to you.`,
	`I don’t owe people anything, and I don’t have to talk to them any more than I feel I need to.`,
	`your love will be  misunderstood,  your love will be  taken for granted,  your love will go  through trials until  it finds a home.`,
	`Be stubborn about your goals but flexible about your methods.`,
	`So plant your own gardens and decorate your own soul, instead of waiting for someone to bring you flowers.`,
	`Never underestimate the power of good morning texts, apologies, and random compliments.`,
	`Still, being able to feel pain was good, he thought. It’s when you can’t even feel pain anymore that you’re in real trouble.`,
	`I don’t want to remind you of anyone. I want to be the first me you’ve ever met.`,
	`You can’t change the past, so focus on making a great future.`,
	`My pulse now echoes your name.`,
	`I only write when I am falling in love, or falling apart.`,
	`It is not enough to have a good mind; the main thing is to use it well.`,
	`That’s what careless words do. They make people love you a little less.`,
	`Stop giving people power to control your smile, your worth, and your attitude.`,
	`Everyday is a new opportunity to be a better person.`,
	`There’s a beautiful thing that happens inside you when you care about someone.`,
	`You have to find the right distance between people. Too close, and they overwhelm you, too far and they abandon you.`,
	`Looks don’t mean everything. I’d rather have a beautiful conversation than a pretty face to look at.`,
	`I really don’t know what ‘I love you’ means. I think it means ‘Don’t leave me here alone.’`,
	`I love like a leaky faucet or I love like a dam breaking. There is nothing in between.`,
	`Running away from your problems is a race you’ll never win.`,
	`You’re like the rain… an old friend, with bad timing.`,
	`You either say how you feel and fuck it up or say nothing and let it fuck you up instead.`,
	`…Sometimes you don’t have to be mean to hurt someone.`,
	`If they don’t fight for you, they’re not right for you.`,
	`I want to taste your lips before coffee and your skin before sunshine.`,
	`I want to meet people with fire in them, burning through life like a forest fire, too many people die out and survive on embers.`,
	`Be with someone who is proud to have you.`,
	`You know you are doing well when you lose the interest of looking back.`,
	`Don’t give up on things that make you smile.`,
	`I think too much. I think ahead. I think behind. I think sideways. I think it all. If it exists, I’ve fucking thought of it.`,
	`You’ll meet her, she’s very pretty, even though sometimes she’s sad for many days at a time. You’ll see, when she smiles, you’ll love her.`,
	`One day you will meet someone who will make this messy and hard life easier than you ever thought possible. And you will want to stay.`,
	`You’re not a bad person for the ways you tried to kill your sadness.`,
	`You can, you should, and if you’re brave enough to start, you will.`,
	`Train yourself to write everyday. Even if you have nothing to write, write and say so.`,
	`It is better to be loved by one person who knows your soul than millions who don’t even know your phone number.`,
	`I have discovered in life that there are ways of getting almost anywhere you want to go, if you really want to go.`,
	`I have no problem texting first as long as you make me feel like you actually wanna talk.`,
	`Calling someone ugly won’t make you beautiful.`,
	`I hate this feeling of not knowing what you’re feeling.`,
	`It’s not weak to cry  It’s human  It’s weak not to try  And it’s sad  That some fear emotion  And think love  Is an evil potion`,
	`I’m fine, I’m just not happy.`,
	`Damaged people are dangerous. They know how to make hell feel like home.`,
	`Friendship is better than relationship.`,
	`Your future self is watching you right now through memories.`,
	`Go for it. Whether it ends good or bad, it was an experience.`,
	`One bad relationship could make you never want to fall in love again.`,
	`don’t judge a book by its a cover, but judge a crying poet`,
	`I learned that people leave. Even if they have promised a thousand times that they won’t.`,
	`Try to see the good in everyone.`,
	`Sometimes you forgive people simply because you still want them in your life.`,
	`Sometimes all you need to do is just worry about yourself.`,
	`Maybe it won’t work out. But maybe seeing if it does will be the best adventure ever.`,
	`Don’t ever think I fell for you, or fell over you. I didn’t fall in love, I rose in it. I saw you and made up my mind.`,
	`True love is the ability so see something in a person that no one else does.`,
	`Spend a little more time trying to make something of yourself, and a little less time trying to impress everyone.`,
	`Mess around and lose the one person who's always been there for you, and I promise you're gonna be more hurt than they are.`,
	`Don’t force someone to make time for you, if they really want to, they will.`,
	`Don’t lose yourself trying to love someone.`,
	`You’re afraid because people can move on.`,
	`Be a good person. A good friend. Live the life you want. Follow your dreams.`,
	`just remember not everyone has the same heart as you`,
	`All good things are worth waiting for and worth fighting for.`,
	`It's crazy how things change so fast.`,
	`life is so much simpler when you stop explaining yourself to people and just do what works for you`,
	`Keep reminding yourself of your goals, keep telling yourself why exactly you're doing what you're doing.`,
	`I poured everything I had into you, and you were still empty.`,
	`I’m at that point where I don’t even care if people like me anymore. If you like me, cool. If you don’t, okay`,
	`Stop overthinking. Relax and let it go.`,
	`People come and go, but life is simply about seeing who cares enough to stay.`,
	`Stay loyal to the people you love. Loyalty is everything.`,
	`We do not remember days, we remember moments..`,
	`Life is like a mirror. Smile at it and it smiles back at you.`,
	`Truth is I’m a fucking romantic. I’m difficult but I promise I’m not boring.`,
	`Never ignore someone who cares for you, because someday you’ll realize you’ve lost a diamond while you were busy collecting stones.`,
	`I’d do it all over again, you know. I wouldn’t trade one second if it meant we were right here, in this moment.`,
	`Sometimes the bad things that happen in our lives put us directly on the path to the best things that will ever happen to us.`,
	`I want to write a novel about silence. The things people don’t say.`,
	`I'm sorry I have trust issues, but when you give someone everything and they toss it away like nothing, something inside of you breaks 💔`,
	`Sometimes your heart needs more time to accept what your mind already knows.`,
	`It’s not about having the perfect relationship, it’s about finding someone who matches you and will go through everything without giving up.`,
	`you deserve someone who never stops trying to show how much you mean to them, even after they have you`,
	`Never be afraid to be yourself.`,
	`Don’t cling to things because everything is impermanent.`,
	`To the world you might be one person, but to one person you might be the world`,
	`Time decides who you meet in life, your heart decides who you want in you life and your behavior decides who stays in your life.`,
	`Don’t stress. Do your best. Forget the rest.`,
	`You can’t change how people feel about you, so don’t try. Just live your life and be happy.`,
	`When a flower doesn’t bloom you fix the environment in which it grows, not the flower.`,
	`But that’s love, to give away everything, to sacrifice everything, without the slightest desire to get anything in return.`,
	`I asked her if she believed in love, and she smiled and said it was her most elaborate method of self-harm.`,
	`I know I’m unloveable, you don’t have to tell me.`,
	`Open your mind before your mouth.`,
	`If a person made you smile and laugh as loud as you can imagine, that person can also make you cry harder than what you have ever imagined.`,
	`It is sad when someone you know becomes someone you knew.`,
	`Play with her hair, tell her you love her, be weird together, run in the streets, slow dance together, hold her hand, kiss in the rain.`,
	`I’m always tired but never of you`,
	`im so fucking tired of not being a multimillionaire`,
	`The past is behind, learn from it. The future is ahead, prepare for it. The present is here, live it.`,
	`If you don’t fight for what you want, don’t cry for what you lost..`,
	`She wasn’t bitter. She was sad, though. But it was a hopeful kind of sad. The kind of sad that just takes time. `,
	`Always end the day with a positive thought; no matter how hard things were. Tomorrow is a fresh opportunity to make it better.`,
	`avoid disappointments by expecting nothing`,
	`I like people who can keep the conversation going no matter how random the topics get.`,
	`I notice everything, I just act like I don’t.`,
	`Don’t rush anything. When the time is right, it’ll happen.`,
	`I hope one day you find someone who makes flowers grow even in the saddest parts of you.`,
	`Just because a person smiles all the time, doesn't mean their life is perfect.`,
	`Memories are dangerous things. You turn them over and over, until you know every touch and corner, still, you’ll find an edge to cut you.`,
	`The ones who notice the storms in your eyes, the silence in your voice and the heaviness in your heart are the ones you need to let in.`,
}
